#%RAML 0.8

baseUri: https://vapi.ca.com/
version: 1

/book:
  displayName: Books
  get:
    description: Returns a list of all books
    responses:
        200:
          body:
            application/json:
              example: |
                [{
                  "idtype" : "OCLC",
                  "id" : "9506808"
                  "title" : "The Wonderful Wizard of Oz",
                  "author" : "L. Frank Baum"
                },
                {
                  "idtype" : "OCLC",
                  "id" : "236914",
                  "title" : "Kim",
                  "author" : "Rudyard Kipling"
                },
                {
                  "idtype" : "ISBN",
                  "id" : "978-0-670-22026-7"
                  "title" : "Christine",
                  "author" : "Stephen King"
                }]

  /{title}:
    displayName: getBook
    get:
      description: Returns the specified book
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "title" : "{title}",
                  "author" : "{{=[:First Name:]}} {{=[:Middle Initial:]}} {{=[:Last Name:]}}"
                }
