#%RAML 0.8
---
title: e-BookMobile API
baseUri: http://api.e-bookmobile.com/{version}
version: v1

/books:
   /{Title}:
     get:
       description: Retrieve a specific book title
       responses:
         200:
           body:
             application/json:
              example: |
                 {
  "data": {
    "id": {{=[DDDDDDDDDDD]}},
    "title": {Title},
    "publishdate": {{=[:Birthday:]}},
    "publisherloc": {{=[:Country:]}} {{=[:City:]}} {{=[:State Code:]}},                      
    "price":${{=[DD/./DD]}}
    "genre": {{=[Fiction,Non-Fiction]}},
    "author": {{=[:First Name:]}} {{=[:Middle Initial:]}} {{=[:Last Name:]}}
  },
  "success": true,
  "status": 200
}
